spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_service_db
    username: dbuser
    password: dbuser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    sql: info
    web: info

server:
  port: 8080
